#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else "geoavil")
APP = ROOT / "app"


def write(path: Path, content: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


# alpha3 deliberately keeps the alpha1 Shizuku backend generated by
# modernize_geoavil.py + root_system_hook.py. alpha2's wait/fallback rewrite caused
# setupProviders() to return false while Shizuku was granted, leaving both spoofing
# and the UI in a false-success state.
build = APP / "build.gradle"
text = build.read_text(encoding="utf-8")
text = text.replace('versionCode 30001', 'versionCode 30003')
text = text.replace('versionName "0.3.0-alpha1"', 'versionName "0.3.0-alpha3"')
build.write_text(text, encoding="utf-8")

# Keep the original alpha1 analog behaviour and only make WindowManager operations
# non-fatal. Start is invoked from MainActivity's UI thread, so no asynchronous overlay
# lifecycle rewrite is necessary here.
write(APP / "src/main/java/com/github/fakegps/ui/JoyStickView.java", r'''package com.github.fakegps.ui;

import android.content.Context;
import android.graphics.PixelFormat;
import android.os.Build;
import android.provider.Settings;
import android.view.Gravity;
import android.view.LayoutInflater;
import android.view.MotionEvent;
import android.view.View;
import android.view.WindowManager;
import android.widget.FrameLayout;
import android.widget.Toast;

import com.github.fakegps.IJoyStickPresenter;
import com.github.fakegps.JoyStickManager;
import com.github.fakegps.ScreenUtils;
import com.tencent.fakegps.R;

import tiger.radio.loggerlibrary.Logger;

/** Alpha1 analog controller with non-fatal overlay operations. */
public class JoyStickView extends FrameLayout {
    private static final String TAG = "JoyStickView";
    private static int sStatusBarHeight;

    private int mViewWidth;
    private int mViewHeight;
    private WindowManager mWindowManager;
    private WindowManager.LayoutParams mWindowLayoutParams;
    private float mXInScreen;
    private float mYInScreen;
    private float mXInView;
    private float mYInView;
    private boolean isShowing = false;
    private IJoyStickPresenter mJoyStickPresenter;

    public JoyStickView(Context context) {
        super(context);
        mWindowManager = (WindowManager) context.getSystemService(Context.WINDOW_SERVICE);
        LayoutInflater.from(context).inflate(R.layout.joystick_layout, this);

        sStatusBarHeight = ScreenUtils.getStatusBarHeight(context);
        mViewWidth = context.getResources().getDimensionPixelSize(R.dimen.joystick_width);
        mViewHeight = context.getResources().getDimensionPixelSize(R.dimen.joystick_height);

        mWindowLayoutParams = new WindowManager.LayoutParams();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            mWindowLayoutParams.type = WindowManager.LayoutParams.TYPE_APPLICATION_OVERLAY;
        } else {
            mWindowLayoutParams.type = WindowManager.LayoutParams.TYPE_PHONE;
        }
        mWindowLayoutParams.format = PixelFormat.RGBA_8888;
        mWindowLayoutParams.flags = WindowManager.LayoutParams.FLAG_NOT_TOUCH_MODAL
                | WindowManager.LayoutParams.FLAG_NOT_FOCUSABLE;
        mWindowLayoutParams.gravity = Gravity.LEFT | Gravity.TOP;
        mWindowLayoutParams.width = mViewWidth;
        mWindowLayoutParams.height = mViewHeight;
        mWindowLayoutParams.x = Math.max(0, ScreenUtils.getScreenWidth(context) - mViewWidth - 16);
        mWindowLayoutParams.y = Math.max(0, ScreenUtils.getScreenHeight(context) - mViewHeight - 220);

        findViewById(R.id.btn_set_loc).setOnClickListener(mOnClickListener);
        findViewById(R.id.btn_fly_to).setOnClickListener(mOnClickListener);
        findViewById(R.id.btn_bookmark).setOnClickListener(mOnClickListener);
        findViewById(R.id.btn_bookmark).setOnLongClickListener(v -> {
            if (mJoyStickPresenter != null) mJoyStickPresenter.onCopyLocationClick();
            return true;
        });

        findViewById(R.id.btn_hide_joystick).setOnClickListener(v ->
                JoyStickManager.get().hideJoyStick());

        AnalogJoystickView analogJoystick = findViewById(R.id.analog_joystick);
        analogJoystick.setListener(new AnalogJoystickView.Listener() {
            @Override
            public void onMove(float x, float y) {
                if (mJoyStickPresenter != null) mJoyStickPresenter.onAnalogMove(x, y);
            }

            @Override
            public void onRelease() {
                if (mJoyStickPresenter != null) mJoyStickPresenter.onAnalogMove(0f, 0f);
            }
        });
    }

    public void addToWindow() {
        if (isShowing) return;
        try {
            if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.M
                    && !Settings.canDrawOverlays(getContext())) {
                Toast.makeText(getContext(),
                        "Allow Display over other apps to show the analog controller",
                        Toast.LENGTH_LONG).show();
                return;
            }
            if (mWindowManager == null) return;
            mWindowManager.addView(this, mWindowLayoutParams);
            isShowing = true;
        } catch (Throwable t) {
            Logger.e(TAG, "Unable to show analog overlay", t);
            isShowing = false;
            Toast.makeText(getContext(),
                    "Analog overlay could not start. Check Display over other apps.",
                    Toast.LENGTH_LONG).show();
        }
    }

    public void removeFromWindow() {
        if (!isShowing) return;
        try {
            if (mWindowManager != null) mWindowManager.removeView(this);
        } catch (Throwable t) {
            Logger.e(TAG, "Unable to remove analog overlay", t);
        } finally {
            isShowing = false;
        }
    }

    public boolean isShowing() {
        return isShowing;
    }

    private final View.OnClickListener mOnClickListener = v -> {
        int id = v.getId();
        if (id == R.id.btn_set_loc) {
            if (mJoyStickPresenter != null) mJoyStickPresenter.onSetLocationClick();
        } else if (id == R.id.btn_fly_to) {
            if (mJoyStickPresenter != null) mJoyStickPresenter.onFlyClick();
        } else if (id == R.id.btn_bookmark) {
            if (mJoyStickPresenter != null) mJoyStickPresenter.onBookmarkLocationClick();
        }
    };

    public void setJoyStickPresenter(IJoyStickPresenter joyStickPresenter) {
        mJoyStickPresenter = joyStickPresenter;
    }

    @Override
    public boolean onTouchEvent(MotionEvent event) {
        switch (event.getAction()) {
            case MotionEvent.ACTION_DOWN:
                mXInView = event.getX();
                mYInView = event.getY();
                break;
            case MotionEvent.ACTION_MOVE:
                mXInScreen = event.getRawX();
                mYInScreen = event.getRawY() - sStatusBarHeight;
                updateViewPosition();
                break;
            default:
                break;
        }
        return true;
    }

    private void updateViewPosition() {
        mWindowLayoutParams.x = (int) (mXInScreen - mXInView);
        mWindowLayoutParams.y = (int) (mYInScreen - mYInView);
        try {
            if (isShowing && mWindowManager != null) {
                mWindowManager.updateViewLayout(this, mWindowLayoutParams);
            }
        } catch (Throwable t) {
            Logger.e(TAG, "Unable to move analog overlay", t);
        }
    }
}
''')

# alpha1 created the overlay outside any guard. Catch constructor/inflation failures too,
# but keep the exact same synchronous lifecycle and backend behaviour.
manager = APP / "src/main/java/com/github/fakegps/JoyStickManager.java"
m = manager.read_text(encoding="utf-8")
old_show = '''    public void showJoyStick() {
        if (mJoyStickView == null) {
            mJoyStickView = new JoyStickView(mContext);
            mJoyStickView.setJoyStickPresenter(this);
        }

        if (!mJoyStickView.isShowing()) {
            mJoyStickView.addToWindow();
        }
    }
'''
new_show = '''    public void showJoyStick() {
        try {
            if (mJoyStickView == null) {
                mJoyStickView = new JoyStickView(mContext);
                mJoyStickView.setJoyStickPresenter(this);
            }

            if (!mJoyStickView.isShowing()) {
                mJoyStickView.addToWindow();
            }
        } catch (Throwable t) {
            Logger.e(TAG, "Failed to create/show analog controller", t);
            mJoyStickView = null;
            Toast.makeText(mContext,
                    "Analog controller could not start. Location spoofing will keep running.",
                    Toast.LENGTH_LONG).show();
        }
    }
'''
if old_show not in m:
    raise SystemExit("Expected alpha1 JoyStickManager.showJoyStick() not found")
m = m.replace(old_show, new_show)
manager.write_text(m, encoding="utf-8")

print("GeoAvil alpha3 minimal regression fix applied")
